# payment-service/Dockerfile
# Option A : Image Python officielle
FROM python:3.10-slim

# Option B : Image plus légère Alpine
# FROM python:3.11-alpine
# RUN apk add --no-cache gcc musl-dev linux-headers

# Définir le répertoire de travail
WORKDIR /app

# Copier les dépendances d'abord (optimisation cache Docker)
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 5000

# Commande de démarrage
CMD ["python", "main.py"]