# frontend/Dockerfile
FROM node:22-alpine

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers de package
COPY package*.json ./

# Installer les dépendances en ignorant les conflits de peer dependencies
RUN npm install --legacy-peer-deps

# Copier le reste du code
COPY . .

# Exposer le port de l'app React
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "start"]
